name: C/C++ CI

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Go to cmake_filesystem
      run: cd cmake_filesystem
    - name: CMake - create Makefile
      run: cmake ./CMakeLists.txt
    - name: make 
      run: make 
